name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.3.0
  http: ^0.12.0
  flutter_spinkit: ^4.1.2
  font_awesome_flutter: ^8.4.0
  weather_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900

  - family: Fredoka
    fonts:
    - asset: fonts/Fredoka.ttf

  - family: Nexie
    fonts:
    - asset: fonts/Nunito-Bold.ttf